name: Flatpak maker

on:
  [workflow_call]

jobs:
  flatpak:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.10
      options: --privileged
    steps:
      - name: Check out repository
        uses: sithlord48/fancy-checkout@v1.0.0
      - name: ls
        run: ls -lR
      - uses: actions/checkout@v4
        with:
          repository: 'flathub/io.github.mpc_qt.mpc-qt'
      - name: ls
        run: ls -lR
      - name: Get version
        run: |
          if [[ "$GITHUB_REF" == *"refs/heads/release/"* ]]; then
            echo "MPC-QT_PACKAGE_VERSION=$(echo $GITHUB_REF | sed 's,refs/heads/release/,,g')">> $GITHUB_ENV
          else
            echo "MPC-QT_PACKAGE_VERSION=continuous">> $GITHUB_ENV
          fi
      - uses: chrisdickinson/setup-yq@v1.0.0
      - name: Prepare Flatpak manifest with modules from Flathub manifest
        run: |
          # wget https://raw.githubusercontent.com/flathub/io.github.mpc_qt.mpc-qt/refs/heads/master/io.github.mpc_qt.mpc-qt.yml
          yq -y --slurp '
            .[0].modules[0].modules = .[1].modules[0].modules
            | .[0]
          ' packaging/flatpak/io.github.mpc_qt.mpc-qt.yml io.github.mpc_qt.mpc-qt.yml \
          > manifest-merged.yml
      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: mpc-qt-${{env.MPC-QT_PACKAGE_VERSION}}-linux-x86_64.flatpak
          manifest-path: manifest-merged.yml
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: false
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mpc-qt-x86_64-Flatpak
          path: ${{github.workspace}}/mpc-qt[-_]*.flatpak
